# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.0.5'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
